version: '2'
services:
    sampleapp-app:
        image: sampleapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://sampleapp-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=sampleapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sampleapp-mongodb:
        extends:
            file: mongodb.yml
            service: sampleapp-mongodb
